name: Publish sample RubyGem to GitHub Packages

############################################################################
# Start the job on all push to main branch as well as allow manual trigger #
############################################################################
on:
  push:
    branches: [ main ]
  workflow_dispatch:

###############
# Set the Job #
###############
jobs:
  push_sample_gem:
    # Name the Job
    name: Build + Publish
    # Set the agent to run on
    runs-on: ubuntu-latest
    # To publish a package, we need write permission
    permissions:
      contents: read
      packages: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
    - name: Checkout code
      uses: actions/checkout@v3

      ###############################
      # Setup required ruby version #
      ###############################
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

      ###############################################################
      # Setup credentials to interact with registry via ruby client #
      ###############################################################
    - name: Setup credentials
      run: |
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOM
          ---
          :github: Bearer ${GEM_HOST_API_KEY}
          EOM
          chmod 0600 ~/.gem/credentials

      ##############################
      # Build the gem from gemspec #
      ##############################
    - name: Build .gem
      run: gem build *.gemspec

      ###############################
      # Publish the gem to registry #
      ###############################
    - name: Publish .gem
      run: gem push --key github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}

